name: Test

on:
  pull_request:
    branches: [main]

jobs:
  placeholder:
    runs-on: ubuntu-latest
    steps:
      - name: Placeholder Step
        run: echo "This is a placeholder job"
        
  test:
    needs: train
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Pull Docker Image
        run: docker pull zahidmiisc/cicd:latest

      - name: Run Docker Container
        run: docker run zahidmiisc/cicd:latest

      - name: Execute Test Condition
        run: OUTPUT=$(docker run zahidmiisc/cicd:latest)
             echo "Score:"
             echo "$OUTPUT"
             if [[ `echo "$OUTPUT 0.30" | awk '{print ($1 < $2)}'` == 1 ]]; then echo "Insufficient Accuracy" && exit 1; fi
