name: Test Docker Image

on:
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Pull Docker Image
        run: |
          docker pull zahidmiisc/myimage:latest

      - name: Run Docker Container
        run: |
          docker run zahidmiisc/myimage:latest

      - name: Execute Test Script
        run: |
          OUTPUT=$(docker run zahidmiisc/myimage:latest)
          echo "Score:"
          echo "$OUTPUT"
          if [[ `echo "$OUTPUT 0.50" | awk '{print ($1 < $2)}'` == 1 ]]; then echo "Insufficient Accuracy" && exit 1; fi
